name: shrine
description: Improve your design and learn to use our advanced component backdrop menu for Flutter.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    